import BetterPrinting as bp
import time

lst = [(4, 7), (6, 5), (8, 1)]

bp.clear()# clears the terminal
time.sleep(2)
draw = bp.draw(20, 20)# creates the canvas once

draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(1)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()# clears the canvas
#
draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(1)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
#
draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(1)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
#
draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(1)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()

draw.turn("down")
# 1
draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(1)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
# 2
draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(1)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
# 3
draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(1)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
# 4
draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(1)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
# 5
draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(1)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
# 6
draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(1)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
# 7
draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(1)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
# 8
lst.remove((lst[0][0], lst[0][1]))
draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(1)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
#######
# 1
draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(2)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
draw.turn("right")
# 2
draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(2)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
draw.turn("up")
# 3
draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(2)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
# 4
draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(2)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
# 5
lst.remove((lst[0][0], lst[0][1]))
draw.place_character(lst[0][0], lst[0][1], "O")
draw.forward(2)
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
######
# 1
draw.place_character(lst[0][0], lst[0][1], "O")
draw.place_character(draw.x, draw.y, "#")
draw.place_character(draw.x, draw.y-1, "#")
draw.place_character(draw.x, draw.y-2, "#")
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
# 2
draw.place_character(draw.x, draw.y-1, "#")
draw.place_character(draw.x, draw.y-2, "#")
draw.place_character(draw.x, draw.y-3, "#")
draw.place_character(lst[0][0], lst[0][1], "O")
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
# 3
draw.place_character(draw.x+1, draw.y-3, "#")
draw.place_character(draw.x, draw.y-3, "#")
draw.place_character(draw.x, draw.y-2, "#")
draw.place_character(lst[0][0], lst[0][1], "O")
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()
# 4
draw.place_character(draw.x+2, draw.y-3, "#")
draw.place_character(draw.x+1, draw.y-3, "#")
draw.place_character(draw.x, draw.y-3, "#")
lst.remove((lst[0][0], lst[0][1]))
draw.done()
time.sleep(0.5)
bp.clear()
draw.clear()


bp.ui.text_box("Y      ", rounded_edges=True)
time.sleep(0.5)
bp.clear()
bp.ui.text_box("YO     ", rounded_edges=True)
time.sleep(0.5)
bp.clear()
bp.ui.text_box("YOU    ", rounded_edges=True)
time.sleep(0.5)
bp.clear()
bp.ui.text_box("YOU W  ", rounded_edges=True)
time.sleep(0.5)
bp.clear()
bp.ui.text_box("YOU WO ", rounded_edges=True)
time.sleep(0.5)
bp.clear()
bp.ui.text_box("YOU WON", rounded_edges=True)
time.sleep(2)